on:
  push:

jobs:
  envsubst-check:
    name: envsubst check
    runs-on: ubuntu-latest

    steps:
      - name: Check if envsubst is available
        run: |
          if ! command -v envsubst &> /dev/null
          then
              echo "envsubst could not be found"
              exit 1
          else
              echo "envsubst is available"
              which envsubst
          fi

      - name: Check if sponge is available
        run: |
          if ! command -v sponge &> /dev/null
          then
              echo "sponge could not be found"
              exit 1
          else
              echo "sponge is available"
              which sponge
          fi
